version: '2.0'
services:
  nginx: 
    image: nginx:latest
    container_name: astro_belnginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./SSL/:/etc/letsencrypt/:ro"
      - "./www:/usr/share/nginx/html:ro"
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
